# Bayesian Models: Naive Bayes and Bayesian Networks
This notebook covers:
- Naive Bayes (GaussianNB)
- Bayesian Networks (using pgmpy library)

In [1]:
# Import libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

## Naive Bayes (GaussianNB)

In [2]:
# Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [3]:
# Train Gaussian Naive Bayes model
nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_pred))
print('\nClassification Report:\n', classification_report(y_test, y_pred))
print('\nConfusion Matrix:\n', confusion_matrix(y_test, y_pred))

Accuracy: 0.9777777777777777

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45


Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


## Bayesian Networks (with pgmpy)

In [4]:
# If pgmpy is not installed, uncomment the line below
# !pip install pgmpy

In [5]:
from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination

# Create a toy dataset
data = pd.DataFrame(data={
    'Cloudy': np.random.choice(['T', 'F'], size=100),
    'Sprinkler': np.random.choice(['T', 'F'], size=100),
    'Rain': np.random.choice(['T', 'F'], size=100),
    'WetGrass': np.random.choice(['T', 'F'], size=100)
})

/Users/jasonrobinson/my-data-science-journey-3/ds_journey_env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
# Define the structure of the Bayesian Network
model = BayesianModel([('Cloudy', 'Sprinkler'),
                       ('Cloudy', 'Rain'),
                       ('Sprinkler', 'WetGrass'),
                       ('Rain', 'WetGrass')])

# Estimate parameters using MLE
model.fit(data, estimator=MaximumLikelihoodEstimator)

/Users/jasonrobinson/my-data-science-journey-3/ds_journey_env/lib/python3.12/site-packages/pgmpy/models/BayesianModel.py:8: FutureWarning: BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
  warnings.warn(


In [7]:
# Perform inference
infer = VariableElimination(model)
posterior = infer.query(['WetGrass'], evidence={'Rain': 'T'})
print(posterior)

+-------------+-----------------+
| WetGrass    |   phi(WetGrass) |
+=============+=================+
| WetGrass(F) |          0.4369 |
+-------------+-----------------+
| WetGrass(T) |          0.5631 |
+-------------+-----------------+


/Users/jasonrobinson/my-data-science-journey-3/ds_journey_env/lib/python3.12/site-packages/pgmpy/models/BayesianModel.py:8: FutureWarning: BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
  warnings.warn(
